apiVersion: v1
kind: Service
metadata:
  name: {{ include "keda-poc.fullname" . }}
  labels:
    {{- include "keda-poc.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 9095
      targetPort: 9095
      protocol: TCP
      name: management
  selector:
    {{- include "keda-poc.selectorLabels" . | nindent 4 }}
